version: "3"

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: base
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    volumes:
      - ./data:/data
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_URI: mongo://base:example@mongo:27017/admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: base
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
